/**
 * Study Plan Status
 */
export enum StudyPlanStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  ARCHIVED = 'ARCHIVED',
}

/**
 * Study Plan Entity
 */
export class StudyPlan {
  constructor(
    public readonly id: string,
    public readonly userId: string,
    public readonly startDate: Date,
    public readonly endDate: Date,
    public readonly content: StudyPlanContent,
    public readonly status: StudyPlanStatus,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
  ) {}

  /**
   * Check if plan is active
   */
  isActive(): boolean {
    return this.status === StudyPlanStatus.ACTIVE;
  }

  /**
   * Check if plan is completed
   */
  isCompleted(): boolean {
    return this.status === StudyPlanStatus.COMPLETED;
  }

  /**
   * Get duration in days
   */
  getDurationDays(): number {
    return Math.ceil((this.endDate.getTime() - this.startDate.getTime()) / (1000 * 60 * 60 * 24));
  }

  /**
   * Get progress percentage
   */
  getProgress(): number {
    const totalTasks = this.content.days.reduce((sum, day) => sum + day.tasks.length, 0);
    const completedTasks = this.content.days.reduce(
      (sum, day) => sum + day.tasks.filter((t) => t.completed).length,
      0,
    );
    return totalTasks === 0 ? 0 : (completedTasks / totalTasks) * 100;
  }

  static fromDTO(dto: StudyPlanDTO): StudyPlan {
    return new StudyPlan(
      dto.id,
      dto.userId,
      new Date(dto.startDate),
      new Date(dto.endDate),
      typeof dto.content === 'string' ? JSON.parse(dto.content) : dto.content,
      dto.status as StudyPlanStatus,
      new Date(dto.createdAt),
      new Date(dto.updatedAt),
    );
  }

  toDTO(): StudyPlanDTO {
    return {
      id: this.id,
      userId: this.userId,
      startDate: this.startDate.toISOString(),
      endDate: this.endDate.toISOString(),
      content: typeof this.content === 'string' ? this.content : JSON.stringify(this.content),
      status: this.status,
      createdAt: this.createdAt.toISOString(),
      updatedAt: this.updatedAt.toISOString(),
    };
  }
}

export interface StudyPlanDTO {
  id: string;
  userId: string;
  startDate: string;
  endDate: string;
  content: string | StudyPlanContent;
  status: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * Study Plan Content Structure
 */
export interface StudyPlanContent {
  title: string;
  description: string;
  days: StudyDay[];
}

export interface StudyDay {
  date: string; // YYYY-MM-DD
  tasks: StudyTask[];
}

export interface StudyTask {
  id: string;
  lesson: string;
  topic: string;
  duration: number; // minutes
  completed: boolean;
  notes?: string;
}

/**
 * Generate Study Plan Request
 */
export interface GenerateStudyPlanRequest {
  // Empty body - generated by AI based on user data
}

/**
 * Generate Study Plan Response
 */
export interface GenerateStudyPlanResponse {
  id: string;
  startDate: string;
  endDate: string;
  content: StudyPlanContent;
  status: StudyPlanStatus;
}
